---
- name: Install Nginx
  apt:
    name: nginx
    state: present
- name: Remove nginx default configuration
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
- name: create a custom gzip.conf 
  template:
    src: gzip.conf 
    dest: /etc/nginx/conf.d/gzip.conf
- name: create a custom nginx configuration
  template:
    src: nginx-config
    dest: /etc/nginx/sites-available/default
  notify:
  - restart nginx
- file:
    path: /etc/nginx/sites-available/default
    owner: root
    group: root