- hosts: all
  become: yes
  become_method: sudo
  remote_user: packer

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  
  roles:
    - dependecies
    - vault
    - logging
    - move_files
