---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
- name: Add elasticsearch apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Add filebeat repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    state: present
    update_cache: yes
- name: Install filebeat and metricbeat package
  apt:
    name: ['filebeat', 'metricbeat']
    state: present
- name: configure the Beat to start automatically during boot
  command: update-rc.d filebeat defaults 95 10
- name: create credentials directory
  file:
    path: /etc/pki/tls/certs
    state: directory
- name: template out logstash crendential files to cert directory
  template:
    src: logstash-forwarder.crt
    dest: /etc/pki/tls/certs/logstash-forwarder.crt
- name: move default filebeat config
  command: mv /etc/filebeat/filebeat.yml /etc/filebeat/filebeat.old.yml
- name: template out custom filebeat config
  template:
    src: filebeat-config.yml.templ
    dest: /etc/filebeat/filebeat.yml
- name: enable filebeat
  command: filebeat modules enable nginx system
  notify:
  - restart filebeat
- name: configure the Beat to start automatically during boot
  command: update-rc.d filebeat defaults 95 10