---
# install dependencies

- name: update ubuntu
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependencies
  apt:
    name: ['python3-dev', 'python3-pip', 'supervisor']

- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
