---
- name: run apt-get update
  apt:
    update_cache: yes
- name: Install iptables
  apt:
    name: iptables
    state: present
- name: Setting up packet masquerading
  command: iptables -t nat -A POSTROUTING -o ens4 -j MASQUERADE
- name: Enabling packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present